---
title: "cest1.2_AnteriorTouch"
author: "Julia_Mike"
date: "6/15/2021"
output: 
  html_document:
    code_folding: hide
    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(patchwork)
library(ggbeeswarm)
library(kableExtra)
library(magrittr)
theme_set(theme_classic())
```

```{r data load, message=FALSE}
AntTouch <- read_csv('cest1.2_anterior_touch_merged.csv') %>%
  mutate(plate = as.factor(plate))
```

```{r}
(bodybendPlot <- AntTouch %>%
  filter(is.na(note), time_off_food != 30, is.na(additive), genotype != "daf-22",
         food == "OP50") %>%
  ggplot(aes(x = date, fill = genotype, y = bends)) +
  geom_boxplot() +
  ggbeeswarm::geom_quasirandom(aes(group = genotype),
                               width = .1,
                               alpha = 0.3,
                               dodge.width = .75) +
  stat_summary(aes(color = genotype),
               geom = "errorbar", 
               fun.data = "mean_se", 
               width = 0.1, 
               position = position_dodge(width = 1.6)) +
  scale_color_brewer(palette = "Accent") +
  scale_fill_brewer(palette = "Accent") +
   labs(title = "Body bends in anterior touch response",
 y = "number of body bends per reversal") +
   stat_summary(aes(shape = genotype), fun = mean, geom = "point",
                color = "red", size = 2))
  

#Are num bends dependent on time on plate? 
#(bends_by_order <- AntTouch %>%
 # group_by(genotype, time_off_food, observer) %>%
#  mutate(index = row_number()) %>%
 # ggplot(aes(x = index, y = bends)) +
#    geom_point()) +
#  facet_grid(time_off_food ~ genotype, scales = "free_y") +
#  geom_smooth(method = "lm")

```

```{r means by group}
  

# get group means:

AntTouch %>%
  filter(time_off_food != 30, is.na(note), is.na(additive), food == "OP50") %>%
  group_by(genotype, observer) %>%
  summarize(mean_bends = mean(bends)) %>%
  kable() %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))

```


```{r body bends by time 3 days}
# plot the distribution of body bends:
AntTouch %>%
  filter(time_off_food != 30, is.na(note), is.na(additive), food == "OP50") %>%
  ggplot(aes(x = bends)) +
  geom_freqpoly(aes(color = genotype, y = stat(count) / sum(count)), stat = "bin", bins = 6)


# or density plot:
AntTouch %>%
  filter(time_off_food != 30, is.na(note)) %>%
  ggplot(aes(x = bends, fill = genotype, colour = genotype)) +
  geom_density(aes(color = genotype), alpha = 0.1, adjust = 2) +
  xlim(0,10)

```

```{r tail touch}
AntTouch$tail_touch_logical <- AntTouch$tail_touch == "Y"
# ok so this works if you have the same number of observations, 
# a better way below
tailtouchPlot <- AntTouch %>%
  #filter(NumBends < 10) %>%
  filter(is.na(note), is.na(additive),  food == "OP50") %>%
  ggplot(aes(x = genotype, y = tail_touch , colour = date)) +
  stat_summary(fun.y = sum, geom = "bar") +
  facet_grid(date ~time_off_food)
tailtouchPlot

(tailtouchPlot2 <- 
  AntTouch %>%
    ungroup() %>%
  filter(is.na(note), is.na(additive),  food == "OP50", genotype != "daf-22") %>%
  ggplot(aes(x = genotype, fill = tail_touch)) +
    # if you don't choose position = "fill", it will give you counts, not proportion
    geom_bar(position = "fill") +
  labs(title = "Tail touch probability in cest-1.2",
       y = "proportion of tail touch events") +
  facet_grid(.~date) +
    scale_fill_brewer(palette = "Pastel2", direction = -1))

```

```{r plot both, fig.height=8, fig.width = 10}
bodybendPlot2 <- AntTouch %>%
  #filter(NumBends < 10) %>%
  filter(is.na(note), time_off_food != 30, is.na(additive), food == "OP50") %>%
  ggplot(aes(x = 1, fill = genotype, y = bends)) +
  geom_boxplot() +
  ggbeeswarm::geom_quasirandom(aes(group = genotype),
                               width = .1,
                               alpha = 0.3,
                               dodge.width = .75) +
  stat_summary(aes(color = genotype),
               geom = "errorbar", 
               fun.data = "mean_se", 
               width = 0.1, 
               position = position_dodge(width = 1.6)) +
  scale_color_brewer(palette = "Accent") +
  scale_fill_brewer(palette = "Accent") +
   labs(title = "Body bends in anterior touch response",
 y = "number of body bends per reversal") +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())

tailtouchPlot3 <- 
  AntTouch %>%
    ungroup() %>%
  filter(is.na(note), is.na(additive),  food == "OP50") %>%
  # next line is to fix the typo
  mutate(tail_touch = case_when( 
    tail_touch == "Y" ~ "Y",
    TRUE ~ "N"
  )) %>%
  ggplot(aes(x = genotype, fill = tail_touch)) +
    # if you don't choose position = "fill", it will give you counts, not proportion
    geom_bar(position = "fill") +
  labs(title = "Tail touch probability in cest-1.2",
       y = "proportion of tail touch events") +
    scale_fill_brewer(palette = "Pastel2", direction = -1)

(bodybendPlot / tailtouchPlot2) | (bodybendPlot2 / tailtouchPlot3)


```

```{r some stats}

bayes_mod <- AntTouch %>%
  filter(is.na(note), time_off_food != 30) %>%
  rstanarm::stan_glmer(
  formula = bends ~ genotype + (1|date) + (1|plate),
  family = poisson,
  adapt_delta = 0.99
)

glmm_mod <- AntTouch %>%
  filter(is.na(note), time_off_food != 30) %>%
  lme4::glmer(formula = bends ~ genotype + (1|plate),
  family = poisson
)
# this leads to singular fit so a Bayes approach is better. 


#non hierarchical glm
glm_mod <- AntTouch %>%
  filter(is.na(note), time_off_food != 30) %>%
  glm(formula = bends ~ genotype,
  family = poisson
)

# or to model as log-transformed continuous variable (not ideal)
bayes_linmod <- AntTouch %>%
  filter(is.na(note), time_off_food != 30) %>%
  rstanarm::stan_lmer(
  formula = log(bends) ~ genotype + (1|date) + (1|plate),
  adapt_delta = 0.99
)

```
```{r TA experiment}
(TAbodybendPlot <- AntTouch %>%
  #filter(NumBends < 10) %>%
  filter(is.na(note), time_off_food != 30, food == "OP50", genotype != "daf-22",
         !is.na(additive)) %>%
  ggplot(aes(x = additive, fill = genotype, y = bends)) +
  geom_boxplot() +
  ggbeeswarm::geom_quasirandom(aes(group = genotype),
                               width = .1,
                               alpha = 0.3,
                               dodge.width = .75) +
  stat_summary(aes(color = genotype),
               geom = "errorbar", 
               fun.data = "mean_se", 
               width = 0.1, 
               position = position_dodge(width = 1.6)) +
  scale_color_brewer(palette = "Accent") +
  scale_fill_brewer(palette = "Accent") +
   labs(title = "Body bends in anterior       
touch response",
 y = "number of body bends per reversal", x = "Plate additive")+ 
  facet_grid(.~ date))

(TAtailtouchPlot <- 
  AntTouch %>%
    ungroup() %>%
    mutate(additive = case_when(
      is.na(additive) ~ 'none',
      TRUE ~ additive)) %>%
  filter(is.na(note),  food == "OP50", additive != "H2O") %>%
  ggplot(aes(x = genotype, fill = tail_touch)) +
    # if you don't choose position = "fill", it will give you counts, not proportion
    geom_bar(position = "fill") +
  labs(title = "Tail touch probability in cest-1.2",
       y = "proportion of tail touch events") +
  facet_grid(.~additive) +
    scale_fill_brewer(palette = "Pastel2", direction = -1))

(TAbodybendPlot | TAtailtouchPlot)
```
```{r tnaA experiment}
(tnaAbodybendPlot <- AntTouch %>%
  #filter(NumBends < 10) %>%
  filter(is.na(note), time_off_food != 30, food != "OP50") %>%
  ggplot(aes(x = food, fill = genotype, y = bends)) +
  geom_boxplot() +
  ggbeeswarm::geom_quasirandom(aes(group = genotype),
                               width = .1,
                               alpha = 0.3,
                               dodge.width = .75) +
  stat_summary(aes(color = genotype),
               geom = "errorbar", 
               fun.data = "mean_se", 
               width = 0.1, 
               position = position_dodge(width = 1.6)) +
  scale_color_brewer(palette = "Accent") +
  scale_fill_brewer(palette = "Accent") +
   labs(title = "Body bends in anterior touch response",
 y = "number of body bends per reversal")) +
  facet_grid(.~ date)

(tnaAtailtouchPlot <- 
  AntTouch %>%
    ungroup() %>%
  filter(is.na(note), food != "OP50") %>%
  ggplot(aes(x = genotype, fill = tail_touch)) +
    # if you don't choose position = "fill", it will give you counts, not proportion
    geom_bar(position = "fill") +
  labs(title = "Tail touch probability in cest-1.2",
       y = "proportion of tail touch events") +
  facet_grid(date ~food) +
    scale_fill_brewer(palette = "Pastel2", direction = -1))

(tnaAbodybendPlot | tnaAtailtouchPlot)

(distribution <- ggplot(AntTouch, aes(x=bends)) +
    geom_histogram(binwidth=.5, colour="black", fill="white")+
    facet_grid(genotype ~ food))
  

```
```{r combined plot}

(TAbodybendPlot | TAtailtouchPlot)/ (tnaAbodybendPlot  | tnaAtailtouchPlot)
```

